new Vue({
	el: '#vue-app',
	data: {
        name: 'John Doe',
        designation:'Software Engineer',
		address: '111 Lorem Street, 34785, Ipsum City',
		phone: '+91 9874563210',
        email: 'johndoe@gmail.com',
        date:'',
        objective:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin dignissim viverra nibh sed varius. Proin bibendum nunc in sem ultrices posuere. Aliquam ut aliquam lacus.',
        sdate:'',
        edate:'',
        schoolname:'',
        schoolocation:'',
        schoolscore:'',
        sdate1:'',
        sdate1:'',
        hschoolname:'',
        hschoolocation:'',
        hschoolscore:'',
        sdate2:'',
        edate2:'',
        collegename:'',
        collegelocation:'',
        collegescore:'',
        c:'',
        java:'',
        htmlcss:'',
        js:'',
        php:'',
        db:'',
        ach1:'',
        ach2:'',
        ach3:'',
        companyname1:'',
        comdesignation1:'',
        sdate3:'',
        edate3:'',
        companylocation1:'',
        cdes1:''
        
	},
	methods: {
		
	}
});